const aliases = {
    'item': {
        'zyzz': 'copper arm',
        'isitaris': 'lifelong protection',
        'executor': 'skull mentor',
        'exe': 'skull mentor',
        'gss': 'greatsword of sharpness',
        'llp':'lifelong protection',
        'bvc':'bane venom charm',
        'bonk':'midget masher',
        'water bottle':'bottle of living water',
        'bop':'braces of protection',
        'friendship':'crown of overmight',
        'friendship hat':'crown of overmight',
        'dai oni':'holy scourge',
        'hamnmer':'dwarven hammer',
        'skeleton':'amulet of the dead',
        'feeblemind':'black bow of botulf',
        'soul slay':'ethereal crossbow',
        'chi boots':'chi shoes',
        'kick shoes':'chi shoes',
        'kick boots':'chi shoes',
        'balrog':'demon whip',
        'balrag':'demon whip',
        'balrug':'demon whip',
        'stealth armor':'shademail haubergeon',
        'holy shield':'immaculate shield',
        'ice king':'crown of the frost king',
        'fire king':'crown of the fire king',
        'buffalo':'headdress of the bull',
        'fear helmet':'horror helmet',
        'ice shield':'ice aegis',
        'frost shield':'ice aegis',
        'rime mail':'rime hauberk',
        'ice mail':'rime hauberk',
        'll':'lightless lantern',
        'pen eye':'eye of the void',
        'aim eye':'eye of aiming',
        'astral hat':'starshine skullcap',
        'naaira':'whip of command',
        'fire skull':'skull of fire',
        'thorn armor':'armor of twisting thorn',
    },
    'spell':{
        'ac': 'astral corruption',
        'sog':'strength of giants',
        'los':'legions of steel',
        'kyuu':'summon air elemental',
        'kyuuman':'summon air elemental',
        'not-lola':'marble warriors',
        'moak':'mother oak',
        'fv':'foul vapors',
        'gfh':'gifts from heaven',
        'goh':'gift of health',
        'rigor':'rigor mortis',
        'wos':'weapons of sharpness',
        'loggy':'gift of reason',
        'magma child':'rhuax pact',
        'magma children':'rhuax pact',
        'l4l':'life for a life',
        'wele':'summon water elemental',
        'fele':'summon fire elemental',
        'aele':'summon air elemental',
        'eele':'summon earth elemental',
        'feast':'blood feast',
        'b banish':'banishment',
        'f banish':'ashes to ashes',
        'w banish':'purifying water',
        'e banish':'pull from the grave',
        'a banish':'wind of memories',
        'n banish':'final rest',
        'd banish':'decree of the underworld',
        's banish':'stellar decree',
        'f smite':'heavenly fire',
        'w smite':'watery death',
        'e smite':'word of stone',
        'a smite':'heavenly strike',
        's strike':'word of power',
        'd smite':'syllable of death',
        'n smite':'word of thorns',
        'b smite':'claim life',
        'rocks':'gifts from heaven',
        'f alchemy':'transmute fire',
        'fire alchemy':'transmute fire',
        'fire gem alchemy':'transmute fire',
        'e alchemy':'alchemical transmutation',
        'longdead':'horde of skeletons',
        'hos':'horde of skeletons',
        'tart':'tartarian gate',
        'big swarm':'creeping doom',
        'vampire':'vampire lord',
        'exe':'dust to dust',
        'executor':'dust to dust',
        "seir":"se'ir",
        'big fish':'summon monster fish',
        'ww':'wailing winds',
        'ffts':'flames from the sky',
        'e power':'earth power',
        'epower':'earth power',
        'lotns':'light of the northern star',
        'ice':'ice strike',
        'big pig':'contact boar of carnutes',
        'biggus piggus':'contact boar of carnutes',
        'tree king':'awaken treelord',
        'f royal':'king of fire',
        'e royal':'king of mountains',
        'a royal':'queen of storms',
        'w royal':'queen of the sea',
        'grigori':'release lord of civilization',
        'vampire':'curse of blood',
        'zan':'fire shield',
        'air dome':'dome of solid air',
        'a dome':'dome of solid air',
        'nature dome':'forest dome',
        'n dome':'forest dome',
        'fire dome':'dome of flaming death',
        'f dome':'dome of flaming death',
        'blood dome':'dome of corruption',
        'b dome':'dome of corruption',
        'astral dome':'dome of arcane warding',
        's dome':'dome of arcane warding',
        'water dome':'frost dome',
        'w dome':'frost dome',
        'disease demon':'infernal disease',
    },
    'site':{
        'best':'lava lake',
    },
    'unit':{
        'chad': 'anakite',
        'exe':'demilich',
        'executor':'demilich',
        'jo brandon':'sequani stargazer',
        'jo':'sequani stargazer',
        'banefire':'king of banefires',
        'helio':'heliophagus',
        'king of water':'queen of water',
        'king of air':'queen of storms',
        'queen of earth':'king of mountains',
        'queen of fire':'king of flames',
        "seir":"se'ir",
        'rovsea':'ryujin',
        'nomad':'floating mind',
        'aethernomad':'floating mind',
        'polybotes':'king of the gigantes',
        'mandarbmax':'king of the gigantes',
        'enkelados':'first of the gigantes',
        'enchenchiladas':'first of the gigantes',
        'enchiladas':'first of the gigantes',
        'txoumin':'first of the gigantes',
        'maerlande':'goat',
        'snot goblin':'bakemono-sho',
        'dai bork':'dai bakemono',
        'fat goblin':'bakemono sorcorer',
        'bob':'lord of the forest',
        'forester bob':'lord of the forest',
        'ea skratti':'553',
        'nifel skratti':'553',
        'ma skratti':'3429',
        'jotun skratti':'3429',
        'la skratti':'3432',
        'utgard skratti':'3432',
        'wele':'water elemental',
        'fele':'fire elemental',
        'aele':'air elemental',
        'eele':'earth elemental',
        'kyuu':'strange bird',
        'kyuumann':'strange bird',
        'not-lola':'demon jester',
        'ea dryad':'2187',
        'ma dryad':'237',
        'la dryad':'705',
        'gold adept': 'adept of the golden order',
        'golden adept':'adept of the golden order',
        'silver adept': 'adept of the silver order',
        'exe':'demilich',
        'executor':'demilich',
        'jo brandon':'sequani stargazer',
        'jo':'sequani stargazer',
        'banefire':'king of banefires',
        'helio':'heliophagus',
        'king of water':'queen of water',
        'king of air':'queen of storms',
        'queen of earth':'king of mountains',
        'queen of fire':'king of flames',
        'rovsea':'ryujin',
        'nomad':'floating mind',
        'aethernomad':'floating mind',
        'polybotes':'king of the gigantes',
        'mandarbmax':'king of the gigantes',
        'enkelados':'first of the gigantes',
        'enchenchiladas':'first of the gigantes',
        'enchiladas':'first of the gigantes',
        'txoumin':'first of the gigantes',
        'vampire':'vampire lord',
        'ea skratti':'553',
        'nifel skratti':'553',
        'ma skratti':'3429',
        'jotun skratti':'3429',
        'la skratti':'3432',
        'utgard skratti':'3432',
        'ozzie':'ozelotl',
        'ozzies':'ozelotl',
        'ea pan':'1535',
        'ma pan':'238',
        'la pan':'706',
        'coinneach':'magus',
        'fuwafuwa':'1434',
        'solstice':'3247',
    },
    'merc':{
        'hannibal': 'elephant corps',
    },
    
}

module.exports = { aliases }

