const commanderAliases = {
    'chad': 'adon',
    'gold adept': 'adept of the golden order',
    'golden adept':'adept of the golden order',
    'silver adept': 'adept of the silver order',
    'exe':'demilich',
    'executor':'demilich',
    'jo brandon':'sequani stargazer',
    'jo':'sequani stargazer',
    'banefire':'king of banefires',
    'helio':'heliophagus',
    'king of water':'queen of water',
    'king of air':'queen of storms',
    'queen of earth':'king of mountains',
    'queen of fire':'king of flames',
    'rovsea':'ryujin',
    'nomad':'floating mind',
    'aethernomad':'floating mind',
    'polybotes':'king of the gigantes',
    'mandarbmax':'king of the gigantes',
    'enkelados':'first of the gigantes',
    'enchenchiladas':'first of the gigantes',
    'enchiladas':'first of the gigantes',
    'txoumin':'first of the gigantes',
    'vampire':'vampire lord',
    'ea skratti':'553',
    'nifel skratti':'553',
    'ma skratti':'3429',
    'jotun skratti':'3429',
    'la skratti':'3432',
    'utgard skratti':'3432',
}

module.exports = { commanderAliases }

