const itemAliases = {
    'zyzz': 'copper arm',
    'isitaris': 'lifelong protection',
    'executor': 'skull mentor',
    'exe': 'skull mentor',
    'gss': 'greatsword of sharpness',
    'llp':'lifelong protection',
    'bvc':'bane venom charm',
    'bonk':'midget masher',
    'water bottle':'bottle of living water',
    'bop':'braces of protection',
    'friendship':'crown of overmight',
    'friendship hat':'crown of overmight',
    'dai oni':'holy scourge',
    'hamnmer':'dwarven hammer',
    'skeleton':'amulet of the dead',
    'feeblemind':'black bow of botulf',
    'soul slay':'ethereal crossbow',
    'chi boots':'chi shoes',
    'kick shoes':'chi shoes',
    'kick boots':'chi shoes',
    'balrog':'demon whip',
    'balrag':'demon whip',
    'balrug':'demon whip',
    'stealth armor':'shademail haubergeon',
    'holy shield':'immaculate shield',
    'ice king':'crown of the frost king',
    'fire king':'crown of the fire king',
    'buffalo':'headdress of the bull',
    'fear helmet':'horror helmet',
    'ice shield':'ice aegis',
    'frost shield':'ice aegis',
    'rime mail':'rime hauberk',
    'ice mail':'rime hauberk',
    'll':'lightless lantern',
    'pen eye':'eye of the void',
    'aim eye':'eye of aiming',
    'astral hat':'starshine skullcap',
    'naaira':'whip of command',
}

module.exports = { itemAliases }

