const spellAliases = {
    'ac': 'astral corruption',
    'sog':'strength of giants',
    'los':'legions of steel',
    'kyuu':'summon air elemental',
    'kyuuman':'summon air elemental',
    'not-lola':'marble warriors',
    'moak':'mother oak',
    'fv':'foul vapors',
    'gfh':'gifts from heaven',
    'goh':'gift of health',
    'rigor':'rigor mortis',
    'wos':'weapons of sharpness',
    'loggy':'gift of reason',
    'magma child':'rhuax pact',
    'magma children':'rhuax pact',
    'l4l':'life for a life',
    'wele':'summon water elemental',
    'fele':'summon fire elemental',
    'aele':'summon air elemental',
    'eele':'summon earth elemental',
    'feast':'blood feast',
    'b banish':'banishment',
    'f banish':'ashes to ashes',
    'w banish':'purifying water',
    'e banish':'pull from the grave',
    'a banish':'wind of memories',
    'n banish':'final rest',
    'd banish':'decree of the underworld',
    's banish':'stellar decree',
    'f smite':'heavenly fire',
    'w smite':'watery death',
    'e smite':'word of stone',
    'a smite':'heavenly strike',
    's strike':'word of power',
    'd smite':'syllable of death',
    'n smite':'word of thorns',
    'b smite':'claim life',
    'rocks':'gifts from heaven',
    'f alchemy':'transmute fire',
    'fire alchemy':'transmute fire',
    'fire gem alchemy':'transmute fire',
    'e alchemy':'alchemical transmutation',
    'longdead':'horde of skeletons',
    'hos':'horde of skeletons',
    'tart':'tartarian gate',
    'big swarm':'creeping doom',
    'vampire':'vampire lord',
    'exe':'dust to dust',
    'executor':'dust to dust',
    "seir":"se'ir",
    'big fish':'summon monster fish',
    'ww':'wailing winds',
    'ffts':'flames from the sky',
    'e power':'earth power',
    'epower':'earth power',
    'lotns':'light of the northern star',
    'ice':'ice strike',
    'big pig':'contact boar of carnutes',
    'biggus piggus':'contact boar of carnutes',
    'tree king':'awaken treelord',
    'f royal':'king of fire',
    'e royal':'king of mountains',
    'a royal':'queen of storms',
    'w royal':'queen of the sea',
    'grigori':'release lord of civilization',
    'vampire':'curse of blood',
    'zan':'fire shield',
    'air dome':'dome of solid air',
    'a dome':'dome of solid air',
    'nature dome':'forest dome',
    'n dome':'forest dome',
    'fire dome':'dome of flaming death',
    'f dome':'dome of flaming death',
    'blood dome':'dome of corruption',
    'b dome':'dome of corruption',
    'astral dome':'dome of arcane warding',
    's dome':'dome of arcane warding',
    'water dome':'frost dome',
    'w dome':'frost dome',
    'summon naiad':'contact naiad',
    'average dominions':'army of rats',
    'wod':'wind of death',
}

module.exports = { spellAliases }
