const unitAliases = {
    'chad': 'anakite',
    'exe':'demilich',
    'executor':'demilich',
    'jo brandon':'sequani stargazer',
    'jo':'sequani stargazer',
    'banefire':'king of banefires',
    'helio':'heliophagus',
    'king of water':'queen of water',
    'king of air':'queen of storms',
    'queen of earth':'king of mountains',
    'queen of fire':'king of flames',
    "seir":"se'ir",
    'rovsea':'ryujin',
    'nomad':'floating mind',
    'aethernomad':'floating mind',
    'polybotes':'king of the gigantes',
    'mandarbmax':'king of the gigantes',
    'enkelados':'first of the gigantes',
    'enchenchiladas':'first of the gigantes',
    'enchiladas':'first of the gigantes',
    'txoumin':'first of the gigantes',
    'maerlande':'goat',
    'snot goblin':'bakemono-sho',
    'dai bork':'dai bakemono',
    'fat goblin':'bakemono sorcorer',
    'bob':'lord of the forest',
    'forester bob':'lord of the forest',
    'skratti':'500',
    'ea skratti':'553',
    'nifel skratti':'553',
    'ma skratti':'3429',
    'jotun skratti':'3429',
    'la skratti':'3432',
    'utgard skratti':'3432',
    'wele':'water elemental',
    'fele':'fire elemental',
    'aele':'air elemental',
    'eele':'earth elemental',
    'kyuu':'strange bird',
    'kyuumann':'strange bird',
    'not-lola':'demon jester',
    'ea dryad':'2187',
    'ma dryad':'237',
    'la dryad':'705',
    'gold adept': 'adept of the golden order',
    'golden adept':'adept of the golden order',
    'silver adept': 'adept of the silver order',
    'exe':'demilich',
    'executor':'demilich',
    'jo brandon':'sequani stargazer',
    'jo':'sequani stargazer',
    'banefire':'king of banefires',
    'helio':'heliophagus',
    'king of water':'queen of water',
    'king of air':'queen of storms',
    'queen of earth':'king of mountains',
    'queen of fire':'king of flames',
    'rovsea':'ryujin',
    'nomad':'floating mind',
    'aethernomad':'floating mind',
    'polybotes':'king of the gigantes',
    'mandarbmax':'king of the gigantes',
    'enkelados':'first of the gigantes',
    'enchenchiladas':'first of the gigantes',
    'enchiladas':'first of the gigantes',
    'txoumin':'first of the gigantes',
    'vampire':'vampire lord',
    'ozzie':'ozelotl',
    'ozzies':'ozelotl',
    'ea pan':'1535',
    'ma pan':'238',
    'la pan':'706',
    'fuwafuwa':'1434',
    'solstice':'3247',
    'pale rider':'longdead horseman',
    'ma royal guard':'134',
    'la royal guard':'2115',
    'shitty vampire':'405',
    'blood rite vampire':'405',
    'shedim':'2073',
}

module.exports = { unitAliases }

