const unitAliases = {
    'chad': 'anakite',
    'exe':'demilich',
    'executor':'demilich',
    'jo brandon':'sequani stargazer',
    'jo':'sequani stargazer',
    'banefire':'king of banefires',
    'helio':'heliophagus',
    'king of water':'queen of water',
    'king of air':'queen of storms',
    'queen of earth':'king of mountains',
    'queen of fire':'king of flames',
    "seir":"se'ir",
    'rovsea':'ryujin',
    'nomad':'floating mind',
    'aethernomad':'floating mind',
    'polybotes':'king of the gigantes',
    'mandarbmax':'king of the gigantes',
    'enkelados':'first of the gigantes',
    'enchenchiladas':'first of the gigantes',
    'enchiladas':'first of the gigantes',
    'txoumin':'first of the gigantes',
    'maerlande':'goat',
    'snot goblin':'bakemono-sho',
    'dai bork':'dai bakemono',
    'fat goblin':'bakemono sorcorer',
    'bob':'lord of the forest',
    'forester bob':'lord of the forest',
    'vampire':'vampire lord',
}

module.exports = { unitAliases }

